demosite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('upload/', include('upload_image.urls', namespace='upload_image')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
  File Name：   urls
  Description : MiniMES Company
  Author :    Karo Lin
  date：     2022/10/26
  Copyright follow MIT definitions.
-------------------------------------------------
  Change Activity:
          2022/10/26:
-------------------------------------------------
"""
__author__ = 'Karo Lin'

from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
]

upload_image/urls.py
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
  File Name：   urls
  Description : MiniMES Company
  Author :    Karo Lin
  date：     2022/10/25
  Copyright follow MIT definitions.
-------------------------------------------------
  Change Activity:
          2022/10/25:
-------------------------------------------------
"""
__author__ = 'Karo Lin'

from django.urls import path

from upload_image import views

app_name = 'upload_image'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/delete/', views.delete, name='delete'),
    path('<int:image_id>/update/', views.update, name='update'),
]

home/models.py
from django.db import models

# Create your models here.

upload_image/models.py
from django.db import models


# Create your models here.
from upload_image.utility import image_path


class Images(models.Model):
    title = models.CharField(max_length=32, verbose_name='Title')
    image = models.ImageField(upload_to=image_path, verbose_name='Image')

home/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request,'home/index.html')

upload_image/views.py
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from upload_image.models import Images


def index(request):
    if request.method == 'POST':
        image_title = request.POST.get('title')
        image_file = request.FILES.get('fileupload')
        new_image = Images()
        new_image.title = image_title
        new_image.image = image_file
        new_image.save()
        print('Save Image %s!!!' % image_title)
        return redirect(reverse('upload_image:index'))
    images_data = Images.objects.all()
    return render(request, 'upload_image/home.html', context={'data': images_data})


def delete(request, image_id):
    print('Image ID:', image_id)
    pick_data = get_object_or_404(Images, pk=image_id)
    print('Delete image: %s' % pick_data.title)
    pick_data.delete()
    return redirect(reverse('upload_image:index'))


def update(request, image_id):
    print('Image ID:', image_id)
    pick_data = get_object_or_404(Images, pk=image_id)
    title = request.POST.get('update_title')
    image_file = request.FILES.get('update_image')
    pick_data.title = title
    pick_data.image = image_file
    # print(image_id)
    # print(title)
    # print(image_file)
    print('Update Image: %s' % pick_data.title)
    pick_data.save()
    return HttpResponseRedirect(reverse('upload_image:index'))


# 刪除使用 FileField 或是 ImageField 儲存的檔案
@receiver(post_delete, sender=Images)  # Sender is the model class name.
def post_save_image(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    try:
        instance.image.delete(save=False)  # instance.(The ImageField Name)
        # print('Remove physical image.')
    except Exception as e:
        print('Error:', e)


# 更新使用 FileField 或是 ImageField 儲存的檔案
@receiver(pre_save, sender=Images)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    try:
        old_img = instance.__class__.objects.get(id=instance.id).image.path
        print(old_img)
        try:
            new_img = instance.image.path
            print(new_img)
        except:
            new_img = None
        if new_img != old_img:
            import os
            if os.path.exists(old_img):
                os.remove(old_img)
    except Exception as e:
        print('Pre Save Info:', e)

home/templates/home/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>
      body{
        background:#ffc107;
      }
    </style>
  </head>
  <body>
  <div class="container">
      <h1>Hello, Friends!</h1>
      <a class="btn btn-success" href="{% url 'upload_image:index' %}" role="button" > Upload Image Demo </a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

upload_image/templates/upload_image/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Upload File</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>
        body {
            background: #1edc42;
        }
    </style>
</head>
<body>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-12 mb-30">
                <br>
                <h4>Upload file with Model</h4>

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="text" name="title" class="form-control" id="title" placeholder="Title" required>
                    <input type="file" onchange="ShowName()"  name="fileupload" class="form-control" id="upload" required>
                    <input class="form-control btn btn-warning" type="submit" value="Upload">
                </form>

            </div>

            <div class="col-lg-3 col-md-6 col-sm-12 mb-30">
                <img src="{% static 'upload_image/images/MES Logo.png' %}" alt="Logo" style="height:150px">
                <h4>Django Image upload with Model Field.</h4>
                <h4>Django 使用影像模組上傳圖片介紹。</h4>
            </div>

        </div>
            <br><hr>
        <div class="row">
            {% for icon in data %}
                <div class="col-lg-3 col-md-6 col-sm-12 mb-30">
                    <div class="card mt-3" >
                        <!-- Button trigger modal -->
                        <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal{{ icon.id }}">
                        <img src="{{ icon.image.url }}" class="card-img-top" alt="{{ icon.Title }}" style="height: 200px;">
                        </a>
                        <div class="card-body">
                            <p class="card-text">{{ icon.title }}</p>
                            <a href="{% url 'upload_image:delete' icon.id %}" class="btn btn-danger">Delete</a>
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Modal{{ icon.id }}">Update</button>
                        </div>
                    </div>
                </div>
                <!-- Show Image Modal -->
                <div class="modal fade" id="exampleModal{{ icon.id }}" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="ModalLabel">{{ icon.Title }}</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <img src="{{ icon.image.url }}" alt="{{ icon.Title }}" style="width:100%">
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Update Form Modal -->
                <div class="modal fade" id="Modal{{ icon.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">New message</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            <form action="{% url 'upload_image:update' icon.id %}" method="post" enctype="multipart/form-data" id="update_form{{ icon.id }}">
                                {% csrf_token %}
                              <div class="mb-3">
                                <label for="update_title" class="col-form-label">Title:</label>
                                <input type="text" class="form-control" id="update_title" name="update_title" value="{{ icon.title }}" required>
                              </div>
                              <div class="mb-3">
                                <label for="update_image" class="col-form-label">Update Image:</label>
                                <input type="file"  class="form-control" name="update_image" id="update_image"  required>
                              </div>
                            </form>
                          </div>
                          <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                              <input class="btn btn-warning" type="submit" value="UpDate" form="update_form{{ icon.id }}">
                          </div>
                        </div>
                      </div>
                    </div>
            {% endfor %}
        </div>
        <br><hr>
        <div>
            <h4>This is the footer.</h4>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>

    <script>
    function ShowName() {
        var filename = document.getElementById("upload").files[0].name;
        console.log(filename);
        document.getElementById("title").value = filename.split(".")[0];
    }
    </script>
</body>
</html>